name: Build and Release Portfolio Manager

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows
            extension: .exe
            icon: icon.ico
          - os: macos-latest
            platform: darwin
            extension: ""
            icon: icon.png
          - os: ubuntu-latest
            platform: linux
            extension: ""
            icon: icon.png

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xvfb \
          libgtk-3-dev \
          libcairo2-dev \
          libpango1.0-dev \
          libgdk-pixbuf2.0-dev \
          libasound2-dev \
          libglib2.0-dev \
          libffi-dev \
          shared-mime-info

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      env:
        PYTHONIOENCODING: utf-8

    - name: Test Flet import
      run: |
        python -c "import flet; print('Flet import successful')"
        
    - name: Debug environment
      run: |
        echo "Python version: $(python --version)"
        echo "Platform: ${{ matrix.platform }}"
        echo "OS: ${{ matrix.os }}"
        pip list | grep -E "(flet|pyinstaller)"
        
    - name: Build executable using build.py
      run: |
        echo "Building using build.py script..."
        python build.py
      continue-on-error: true
      env:
        PYTHONIOENCODING: utf-8
      
    - name: Alternative build attempt if first failed
      if: failure()
      shell: bash
      run: |
        echo "First build failed, trying direct PyInstaller approach..."
        
        # Determine platform-specific settings
        if [ "${{ matrix.platform }}" = "windows" ]; then
          EXECUTABLE_NAME="PortfolioManager-${{ matrix.platform }}.exe"
          PYINSTALLER_FLAGS="--windowed --icon=icon.ico"
        elif [ "${{ matrix.platform }}" = "darwin" ]; then
          EXECUTABLE_NAME="PortfolioManager-${{ matrix.platform }}"
          PYINSTALLER_FLAGS="--windowed --icon=icon.png"
        else
          EXECUTABLE_NAME="PortfolioManager-${{ matrix.platform }}"
          PYINSTALLER_FLAGS="--console"
        fi
        
        # Run PyInstaller directly
        python -m PyInstaller --onefile $PYINSTALLER_FLAGS \
          --name "portfolio-manager-direct" \
          --add-data "icon.png:." \
          main_flet.py
          
        # Rename the output file to expected name
        if [ -f "dist/portfolio-manager-direct${{ matrix.extension }}" ]; then
          mv "dist/portfolio-manager-direct${{ matrix.extension }}" "dist/$EXECUTABLE_NAME"
          echo "✅ Direct build successful: $EXECUTABLE_NAME"
        elif [ -f "dist/portfolio-manager-direct" ]; then
          mv "dist/portfolio-manager-direct" "dist/$EXECUTABLE_NAME"
          echo "✅ Direct build successful: $EXECUTABLE_NAME"
        else
          echo "❌ Direct build also failed"
          ls -la dist/ || echo "No dist directory"
        fi
      env:
        PYTHONIOENCODING: utf-8
        
    - name: Check build output
      shell: bash
      run: |
        echo "=== Build directory contents ==="
        if [ -d "dist" ]; then
          ls -la dist/
        else
          echo "No dist directory"
        fi
        echo "=== All files in dist ==="
        if [ -d "dist" ]; then
          find dist/ -type f -name "*"
        else
          echo "No files found"
        fi

    - name: Copy and rename artifact if needed
      shell: bash
      run: |
        echo "Looking for built artifacts..."
        if [ -d "dist" ]; then
          expected_name="dist/PortfolioManager-${{ matrix.platform }}${{ matrix.extension }}"
          
          # Check if the expected file already exists
          if [ -f "$expected_name" ]; then
            echo "✅ Target file already exists: $expected_name"
          else
            # Find any built executable and copy it to expected name
            built_file=$(find dist/ -name "PortfolioManager*" -type f | head -1)
            if [ -n "$built_file" ]; then
              echo "Found: $built_file"
              echo "Copying to: $expected_name"
              cp "$built_file" "$expected_name"
              echo "✅ Copied successfully"
            else
              echo "❌ No built files found"
            fi
          fi
          
          echo "Final artifact check:"
          ls -la dist/
        else
          echo "No dist directory found"
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PortfolioManager-${{ matrix.platform }}
        path: dist/PortfolioManager-${{ matrix.platform }}${{ matrix.extension }}
        retention-days: 30
        if-no-files-found: warn

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && always()
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/
      continue-on-error: true

    - name: Display artifact structure
      run: |
        echo "=== Artifact Directory Structure ==="
        find artifacts/ -type f -exec ls -la {} \; || echo "No artifacts found"
        echo "=== End Structure ==="

    - name: Prepare release files
      run: |
        mkdir -p release-files
        
        # Copy available artifacts to release-files directory
        if [ -f "artifacts/PortfolioManager-windows/PortfolioManager-windows.exe" ]; then
          cp "artifacts/PortfolioManager-windows/PortfolioManager-windows.exe" "release-files/"
          echo "✅ Windows executable found"
        else
          echo "❌ Windows executable not found"
        fi
        
        if [ -f "artifacts/PortfolioManager-darwin/PortfolioManager-darwin" ]; then
          cp "artifacts/PortfolioManager-darwin/PortfolioManager-darwin" "release-files/"
          echo "✅ macOS executable found"
        else
          echo "❌ macOS executable not found"
        fi
        
        if [ -f "artifacts/PortfolioManager-linux/PortfolioManager-linux" ]; then
          cp "artifacts/PortfolioManager-linux/PortfolioManager-linux" "release-files/"
          echo "✅ Linux executable found"
        else
          echo "❌ Linux executable not found"
        fi
        
        ls -la release-files/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: release-files/*
        name: Portfolio Document Manager ${{ github.ref_name }}
        body: |
          ## 🎉 Portfolio Document Manager ${{ github.ref_name }}

          ### ✨ Latest Updates - Enhanced User Experience

          Improved window sizing and user interface optimizations for better usability!

          ### 🚀 New Features & Improvements

          - **🖥️ Enhanced Window Size**: Larger default window (1400x1200px) for better content display
          - **📏 Improved Layout**: Better spacing for portfolio tables and interface elements
          - **🎯 Tooltips System**: Hover help for learning outcomes with descriptions and examples
          - **📝 Radio Button Feedback**: Single-selection feedback system for better data consistency
          - **📅 Date/Time Display**: Timestamps in feedback overview for better tracking
          - **🌐 Multi-language Support**: Dutch/English language switching
          - **🌙 Dark/Light Mode**: Toggle between themes
          - **📱 Responsive Design**: Adapts to different screen sizes

          ### 🛠️ Technical Improvements

          - **Modern Flet Framework**: Beautiful, cross-platform UI
          - **Better Window Management**: Improved default sizing and minimum constraints
          - **Enhanced Navigation**: Improved menu structure and user flow
          - **Tooltip Integration**: Contextual help throughout the application
          - **Feedback System**: Radio buttons for single-selection feedback
          - **Cross-platform**: Consistent experience across all OS platforms

          ### 📋 Core Features

          - **Portfolio Management**: Add, edit, and organize portfolio items with tooltips
          - **Feedback System**: Track feedback per learning outcome with date/time stamps
          - **Document Generation**: Export to PDF and Markdown formats
          - **Learning Outcomes**: Detailed information with examples and tooltips
          - **Student Data**: Easy configuration management
          - **Multi-language**: Dutch and English interface support

          ### 📦 Downloads

          Choose your platform:
          - **Windows**: `PortfolioManager-windows.exe`
          - **macOS**: `PortfolioManager-darwin`
          - **Linux**: `PortfolioManager-linux`

          ### 🔧 Installation

          1. Download the executable for your platform
          2. Run the executable (no installation required)
          3. Configure your student information
          4. Start managing your portfolio!

          ### 💻 Development Notes

          - Main application: `main_flet.py`
          - Build script: `build.py`
          - Requirements: See `requirements.txt`
          - Desktop integration files included for Linux

          ---
          
          **🔗 Repository**: https://github.com/RickMageddon/PortfolioDocumentManager
        draft: false
        prerelease: false
        fail_on_unmatched_files: false
        token: ${{ secrets.GITHUB_TOKEN }}
